// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using konyvtar.Data;

#nullable disable

namespace konyvtar.Migrations
{
    [DbContext(typeof(konyvtarContext))]
    [Migration("20240325100711_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("konyvtar.Models.Kolcsonzesek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KolcsonzokId")
                        .HasColumnType("int");

                    b.Property<string>("Mufaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kolcsonzesek");
                });

            modelBuilder.Entity("konyvtar.Models.Kolcsonzok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SzulIdo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kolcsonzok");
                });
#pragma warning restore 612, 618
        }
    }
}
